"""update highlights table with content, line_number, timestamps

Revision ID: 12b3f80317fb
Revises: 770ef4e9e682
Create Date: 2026-01-20 21:52:46.460506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b3f80317fb'
down_revision: Union[str, Sequence[str], None] = '770ef4e9e682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('content', sa.String(), nullable=False))
    op.add_column('highlights', sa.Column('line_number', sa.Integer(), nullable=True))
    op.add_column('highlights', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('highlights', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('highlights', 'note')
    op.drop_index(op.f('ix_repos_url'), table_name='repos')
    op.create_index(op.f('ix_repos_id'), 'repos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repos_id'), table_name='repos')
    op.create_index(op.f('ix_repos_url'), 'repos', ['url'], unique=1)
    op.add_column('highlights', sa.Column('note', sa.VARCHAR(), nullable=True))
    op.drop_column('highlights', 'updated_at')
    op.drop_column('highlights', 'created_at')
    op.drop_column('highlights', 'line_number')
    op.drop_column('highlights', 'content')
    # ### end Alembic commands ###
